export type Interpretation = "F10_WICK"|"F10_BODY"|"F10_STRUCTURAL"|"F11_KEEP"|"F11_DELETE"|"F11_REFRESH"|"F12_TOUCH"|"F12_PENETRATION"|"F12_CLOSE"|"F12_1_CANDLE"|"F12_2_CANDLE"|"F12_3_CANDLE"|"F12_BAR"|"F12_KEY_BAR"|"F14_OBSERVED_D"|"F14_PROJECTED_D"|"F14_WICK"|"F14_BODY"|"F14_STRUCTURAL";
export interface Fixture { id:string; blocker:"F10"|"F11"|"F12"|"F14"; purpose:string; observations:Record<string,number|boolean|string>; candidateInterpretations:Interpretation[]; sourceQuestion:string; }
export const FIXTURES: Fixture[] = [
{id:"F10-DISC-001",blocker:"F10",purpose:"Separate wick, body and structural SL boundaries.",observations:{open:100,high:108,low:96,close:104,structuralLevel:98},candidateInterpretations:["F10_WICK","F10_BODY","F10_STRUCTURAL"],sourceQuestion:"Which exact price field does behind the spike-origin candle identify?"},
{id:"F10-DISC-002",blocker:"F10",purpose:"Separate touch, penetration and close invalidation.",observations:{boundary:96,wickLow:95.9,close:96.2},candidateInterpretations:["F10_WICK","F10_BODY","F10_STRUCTURAL"],sourceQuestion:"What observable price event invalidates the setup?"},
{id:"F11-DISC-001",blocker:"F11",purpose:"Subsequent candle changes stop distance while a pending order exists.",observations:{originalEntry:100,originalStop:90,newStop:92,subsequentCandle:true},candidateInterpretations:["F11_KEEP","F11_DELETE","F11_REFRESH"],sourceQuestion:"Is the old order kept, deleted, or refreshed?"},
{id:"F11-DISC-002",blocker:"F11",purpose:"Two candidate levels compete for one setup.",observations:{candidateA:100,candidateB:101,candidateBNewer:true},candidateInterpretations:["F11_KEEP","F11_DELETE","F11_REFRESH"],sourceQuestion:"What source-defined event makes one candidate supersede another?"},
{id:"F12-DISC-001",blocker:"F12",purpose:"Same level is wicked through but not closed through.",observations:{referenceLevel:100,low:99.8,close:100.3},candidateInterpretations:["F12_TOUCH","F12_PENETRATION","F12_CLOSE"],sourceQuestion:"Does reach mean touch, penetration, or close?"},
{id:"F12-DISC-002",blocker:"F12",purpose:"One-, two-, and three-candle structures overlap.",observations:{candles:3,variant1:true,variant2:true,variant3:true},candidateInterpretations:["F12_1_CANDLE","F12_2_CANDLE","F12_3_CANDLE"],sourceQuestion:"What classifier or precedence applies when variants coexist?"},
{id:"F12-DISC-003",blocker:"F12",purpose:"Bar and Key-Bar confirmations coexist after the same level event.",observations:{levelReached:true,bar:true,keyBar:true},candidateInterpretations:["F12_TOUCH","F12_BAR","F12_KEY_BAR"],sourceQuestion:"Is Bar or Key-Bar mandatory, optional, or variant-specific?"},
{id:"F14-DISC-001",blocker:"F14",purpose:"Observed D and projected equal-leg D are distinct states.",observations:{leg1:20,observedLeg2:18,projectedLeg2:20},candidateInterpretations:["F14_OBSERVED_D","F14_PROJECTED_D"],sourceQuestion:"Is D observed structurally or projected?"},
{id:"F14-DISC-002",blocker:"F14",purpose:"Wick, body and structural endpoints differ.",observations:{wickLeg1:20,bodyLeg1:16,structuralLeg1:18},candidateInterpretations:["F14_WICK","F14_BODY","F14_STRUCTURAL"],sourceQuestion:"Which price representation defines A/B/C/D and leg magnitude?"}
];
export function discriminationPack():Fixture[]{return FIXTURES.map(f=>({...f,candidateInterpretations:[...f.candidateInterpretations]}));}
export function assertNoCanonicalSelection(fixtures:Fixture[]=FIXTURES):void{for(const f of fixtures){if(f.candidateInterpretations.length<2)throw new Error("SOURCE_BOUNDARY_VIOLATION: "+f.id);}}